### ISSUE TITLE
Create the basic dragon

### ISSUE THREAD

**Issue by Ofthemasses** [toru-studio/Gourmandizer#12]
## Description
Now we have the dragons body, a head and maybe a tail needs to be implemented. The head should follow the player, and it should have scrolling textures to make it seems surreal.

## To-Do
- [x] Implement scrolling textures on the dragon body.
- [x] Attach the dragon's head and possibly tail to the body.
- [x] Make a script that makes the dragons head move and follow the player.

**Comment by Ofthemasses** [comment]
On hold until player movement has been implemented
