### ISSUE TITLE
Create player assets and animations

### ISSUE THREAD

**Issue by Ofthemasses** [toru-studio/Gourmandizer#24]
## Describe
Create player assets, animations and pins.

## To-Do:
- [x] Create player assets
- [x] Create walk cycle
- [x] Pin clothes and arms
