### ISSUE TITLE
Create dragon body that is increasable

### ISSUE THREAD

**Issue by Ofthemasses** [toru-studio/Gourmandizer#5]
## Description
We need a hungry dragon that has soft body physics so we can increase it's size.

## To-Do
- [x] Investigate soft-body physics
- [x] Implement a soft body for the dragon's body
- [x] Implement a way to hook into the size of the dragon so it can be increased via gameplay
